<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<main class="main-content" id="main">
    <div class="has-background-black has-text-white has-text-centered py-8">
        <div class="wrapper wrapper--narrower my-8 flow--xl">
            <h1 class="is-size-1 has-text-white"><?php echo tstring('404_title') ?></h1>
            <p><?php echo tstring('404_description') ?></p>
            <a class="button" href="<?php echo __WEB_HOME_URL__ ?>"><?php echo tstring('404_button') ?></a>
        </div>
    </div>
</main>

    <!-- Footer -->
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>
</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
