<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Wrapper. <?php echo trim($template_name) ?> -->
<div id="page-wrapper" class="<?php echo $template_name ?>_content">


    <!-- Main wrapper -->
    <div class="wrapper">
        <h2 class="title">Sorry. Page not found</h2>
        <a class="button" href="<?php echo __WEB_HOME_URL__ ?>"><?php echo tstring('inicio') ?></a>
    </div>

    <!-- Footer -->
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>
</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
