<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Page Wrapper -->
<main class="main-content" id="main">
    <div class="wrapper">
        <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/breadcrumb.phtml'; ?>






        <div class="wrapper mt-8 flow--xl">
            <h1 class="is-sr-only"><?php echo $title ?></h1>
            <div id="items_container"></div>
        </div>

        <!-- Result -->
        <div class="wrapper mt-8 flow--xl" id="rows_list"></div>

    </div>
    <!-- div id="export_data" class="export_data_container"></!-->
</main>
<!-- Footer -->
<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        catalog.set_up({
            row: <?php echo json_encode($this->row) ?>,
            rows_list_container: document.getElementById('rows_list'),
            //export_data_container: document.getElementById('export_data'),
            area_name: <?php echo json_encode($area_name) ?>,
            q: <?php echo json_encode($q) ?>
        })
    })
</script>
