<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<main class="main-content" id="main">
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/breadcrumb.phtml'; ?>
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/text-content.phtml'; ?>

    <!-- Form -->
    <div class="form wrapper flow--2xl">
        <div id="items_container"></div>
        <div id="view_options"></div>
    </div>

    <!-- Result -->
    <div class="result wrapper flow--2xl">
        <div id="rows_list"></div>
    </div>


</main>
<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        thesaurus.set_up({
            table: <?php echo json_encode($thesaurus_options->table) ?>,
            root_term: <?php echo json_encode($thesaurus_options->root_term) ?>,
            term_id: <?php echo json_encode($thesaurus_options->term_id) ?>,
            rows_list: document.getElementById('rows_list')
        })
    })
</script>
