<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Wrapper -->
<div id="page-wrapper">


    <!-- Main wrapper -->
    <div class="wrapper">
        <div class="container">
            <article id="main">

                <!-- title -->
                <h2><?php echo $title ?></h2>

                <!-- abstract -->
                <img id="abstract_icon" class="abstract_icon" src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/icon_info.svg" />
                <div id="abstract" class="hide">
                    <?php echo $abstract ?>
                </div>

                <!-- Form -->
                <section class="form">
                    <div id="items_container"></div>
                    <div id="view_options"></div>
                </section>

                <!-- Result -->
                <section class="result">
                    <div id="rows_list"></div>
                </section>

            </article>
        </div>
    </div>


    <!-- Footer -->
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        thesaurus.set_up({
            table: <?php echo json_encode($thesaurus_options->table) ?>,
            root_term: <?php echo json_encode($thesaurus_options->root_term) ?>,
            term_id: <?php echo json_encode($thesaurus_options->term_id) ?>,
            rows_list: document.getElementById('rows_list')
        })
    })
</script>
