<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<main class="main-content" id="main">
</main>


<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    /*dom_ready(function() {
        main_home.set_up({
            row: <?php echo json_encode($this->row) ?>,
            header_node: document.getElementById('header'),
            carousel_container: document.getElementById('carousel_container')
        })
    })*/
</script>
