<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Page Wrapper -->
<div id="page-wrapper">

    <!-- Main wrapper -->
    <div class="wrapper">
        <div class="container">
            <article id="main">

                <!-- title -->
                <h2><?php echo $title ?></h2>

                <!-- list -->
                <section class="content">
                    <ul>
                        <?php foreach ($list as $item) {
                            if (in_array($item->template_name, $exclude_template_name) || in_array($item->web_path, $exclude_web_path)) {
                                continue;
                            }
                        ?>
                            <li>
                                <a href="<?php echo $item->web_path ?>" title="<?php echo $item->title ?>">
                                    <?php echo $item->term ?>
                                    <?php if (SHOW_DEBUG) echo ' [' . $item->template_name . ']' ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </section>

            </article>
        </div>
    </div>

    <!-- Footer -->
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        sitemap.set_up({})
    })
</script>
