<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Page Wrapper -->
<div id="page-wrapper">

    <!-- Main wrapper -->
    <div class="wrapper">
        <div id="main_info" class="container wide">
            <!-- exhibition_info -->
            <section class="container">
                <div id="exhibition_info"></div>
            </section>
            <!-- current toc item -->
            <section class="container">
                <div id="exhibition_toc"></div>
            </section>
        </div>
        <div class="container">
            <!-- panels -->
            <section>
                <div id="exhibition_toc_item_panels"></div>
            </section>
        </div>
    </div>

    <!-- Footer -->
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        panels.set_up({
            container_exhibition_info: document.getElementById('exhibition_info'),
            container_exhibition_toc_item: document.getElementById('exhibition_toc'),
            container_exhibition_toc_item_panels: document.getElementById('exhibition_toc_item_panels'),
            exhibition_section_id: <?php echo json_encode($exhibition_section_id) ?>,
            toc_panel_section_id: <?php echo json_encode($toc_panel_section_id) ?>,
            toc_panel_key: <?php echo json_encode($toc_panel_key) ?>
        })
    })
</script>
