<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Page Wrapper -->
<main class="main-content" id="main">
    <!-- Main wrapper -->
    <div class="wrapper">
        <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/breadcrumb.phtml'; ?>


        <div class="container wide">
            <!-- exhibition_info -->
            <section class="">
                <div id="exhibition_info"></div>
            </section>
        </div>
        <div class="container">
            <!-- panels -->
            <section class="">
                <div id="exhibition_toc"></div>
            </section>
        </div>



    </div>
</main>
<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        exhibition.set_up({
            container_exhibition_info: document.getElementById('exhibition_info'),
            container_exhibition_toc: document.getElementById('exhibition_toc'),
            section_id: <?php echo json_encode($section_id) ?>
        })
    })
</script>
