<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<main class="main-content" id="main">
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/breadcrumb.phtml'; ?>
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/text-content.phtml'; ?>
    <div id="children_container" class="wrapper flow--2xl">
    </div>
</main>
<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        generic.set_up({
            row: <?php echo json_encode($this->row) ?>,
            children_container: document.getElementById('children_container')
        })
    })
</script>
