<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Page Wrapper -->
<main class="main-content" id="main">
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/breadcrumb.phtml'; ?>
    <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/text-content.phtml'; ?>

    <div class="wrapper">
        <div class="container">
            <article id="main" class="main">

                <!-- body -->
                <div id="row_container" class="<?php echo $web_path ?>"></div>
                <div id="children_container" class="children_container <?php echo $web_path ?>"></div>
            </article>
        </div>
    </div>

</main>
<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        generic.set_up({
            row: <?php echo json_encode($this->row) ?>,
            row_container: document.getElementById('row_container'),
            children_container: document.getElementById('children_container')
        })
    })
</script>
