
<?php if (isset($this->breadcrumb) && count($this->breadcrumb) > 0) : ?>
<div class="is-flex is-justify-content-space-between is-align-items-center gap-4 mb-5">
    <nav class="breadcrumb-nav link-dn is-size-6 has-text-weight-light">
        <ol itemscope="" itemtype="https://schema.org/BreadcrumbList">
            <?php
            $breadCount = 0;
            foreach ($this->breadcrumb as $entry) :
            ?>
            <li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
                <a itemprop="item" href="/<?php echo $entry->web_path ?>">
                    <span itemprop="name"><?php echo $entry->term ?></span>
                </a>
                <meta itemprop="position" content="<?php echo $breadCount + 2 ?>">
            </li>
            <?php
                $breadCount++;
            endforeach
            ?>
        </ol>
    </nav>
    <?php if (isset($this->closeButton) && $this->closeButton) : ?>
    <button id="close-page" type="button" class="button button--icon is-flex-shrink-0">
        <img src="/assets/img/ico-tancar.svg" alt="<?php echo tstring('cerrar'); ?>" width="28" height="28">
    </button>
    <?php endif ?>
</div>
<?php endif ?>
