<?php
$images = null;
if ($this->web_foot->identify_image != null) {
    $images = json_decode($this->web_foot->identify_image, true);
}
if (is_array($images) && count($images) > 0) {
    $image = __WEB_MEDIA_ENGINE_URL__.str_replace('1.5MB', 'original', str_replace('.jpg', '.png', $images[0]));
} else {
    $image = __WEB_ROOT_WEB__.'/assets/img/logo-mupreva.png';
}
?>
    <footer class="pt-8 pb-5 mt-9 has-background-primary has-text-white link-dn is-relative">
        <div class="wrapper">
            <div class="columns is-multiline is-size-6">
                <div class="column is-full-tablet is-one-fifth-widescreen is-2-fullhd has-text-centered-tablet has-text-left-widescreen">
                    <img src="<?php echo $image ?>" alt="<?php echo $this->web_root->title ?>" width="321" height="110">
                </div>
                <div class="column is-hidden-touch is-hidden-desktop-only is-hidden-widescreen-only"></div>

                <?php foreach ($this->web_foot_columns as $column) :
                    if ($column->parent != WEB_FOOT_COLUMNS) {
                        continue;
                    }
                ?>
                    <?php //var_dump($column); ?>
                <div class="column is-one-third-tablet is-one-fifth-widescreen is-2-fullhd">
                    <?php if (!empty($column->identify_image)) : ?>
                    <div class="is-flex gap-2 mb-4">
                        <?php foreach (json_decode($column->identify_image) as $image) : ?>
                        <img src="<?php echo __WEB_MEDIA_ENGINE_URL__.'/'.str_replace('.jpg', '.svg', str_replace('1.5MB', 'original', $image)) ?>" alt="">
                        <?php endforeach ?>
                    </div>
                    <?php endif ?>
                    <?php if (!empty($column->title)) : ?>
                    <p class="is-size-5 mb-4"><?php echo $column->title ?></p>
                    <?php endif ?>
                    <?php if (!empty($column->abstract)) : ?>
                    <div class="flow--m">
                        <div>
                            <?php echo $column->abstract ?>
                        </div>
                    </div>
                    <?php endif ?>
                    <?php
                    $links = [];
                    foreach ($this->web_foot_columns as $subcolumn) :
                        if ($subcolumn->parent != $column->term_id) {
                            continue;
                        }
                        $img = '';
                        if (!empty($subcolumn->identify_image)) {
                            $images = json_decode($subcolumn->identify_image, true);
                            if (is_array($images) && count($images) > 0) {
                                $img = '<img src="'.__WEB_MEDIA_ENGINE_URL__.str_replace('1.5MB', 'original', str_replace('.jpg', '.svg', $images[0])).'" alt="'.$subcolumn->title.'" class="mr-2">';
                            }
                        }
                        $links[] = '<a href="'.$subcolumn->web_path.'">'.$img.$subcolumn->title.'</a>';
                    endforeach ?>
                    <?php
                    if (count($links) > 0) : ?>
                    <ul class="is-flex is-flex-wrap-wrap gap-3">
                        <?php foreach ($links as $link) : ?>
                        <li>
                            <?php echo $link ?>
                        </li>
                        <?php endforeach ?>
                    </ul>
                    <?php endif ?>
                </div>
                <?php endforeach ?>
            </div>
            <div class="is-flex is-flex-wrap-wrap gap-4 is-align-items-flex-end is-justify-content-center">
                <?php
                $links = [];
                foreach ($this->web_foot_logos as $logo) :
                    $img = '';
                    if (!empty($logo->identify_image)) {
                        $images = json_decode($logo->identify_image, true);
                        if (is_array($images) && count($images) > 0) {
                            $img = '<img src="'.__WEB_MEDIA_ENGINE_URL__.str_replace('1.5MB', 'original', $images[0]).'" alt="'.$subcolumn->title.'" class="mr-2">';
                        }
                    }
                    $links[] = '<a href="'.__WEB_ROOT_WEB__.'/'.$logo->web_path.'">'.$img.$logo->title.'</a>';
                endforeach ?>
                <?php
                if (count($links) > 0) : ?>
                    <?php foreach ($links as $link) : ?>
                        <?php echo $link ?>
                    <?php endforeach ?>
                <?php endif ?>


                <ul class="is-flex is-flex-wrap-wrap gap-6 is-justify-content-center mx-auto is-size-6 has-text-weight-medium">
                <?php foreach ($this->menu_footer as $entry) : ?>
                    <li>
                        <a href="<?php echo __WEB_ROOT_WEB__ . '/'.$entry->web_path ?>"><?php echo $entry->title ?></a>
                    </li>
                    <?php endforeach ?>
                </ul>
            </div>
            <a href="#top" aria-label="<?php echo tstring('footer_to_top') ?>" class="scrolltop is-block ml-auto">
                <svg width="50" height="50" xmlns="http://www.w3.org/2000/svg">
                    <g fill="none" fill-rule="evenodd">
                        <path fill="#000" d="M0 50h50V0H0z" />
                        <path stroke="#FFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M15 30.102 25.102 20l10.102 10.102" />
                    </g>
                </svg>
            </a>
        </div>
    </footer>
