    <footer class="pt-8 pb-5 mt-9 has-background-primary has-text-white link-dn">
        <div class="wrapper">
            <div class="columns is-multiline is-size-6">
                <div class="column is-full-tablet is-one-fifth-widescreen is-2-fullhd has-text-centered-tablet has-text-left-widescreen">
                    <img src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/logo-mupreva-footer.png" srcset="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/logo-mupreva-footer@2x.png 2x" alt="<?php echo WEB_ENTITY_LABEL ?>" width="321" height="110">
                </div>
                <div class="column is-hidden-touch is-hidden-desktop-only is-hidden-widescreen-only"></div>
                <div class="column is-one-third-tablet is-one-fifth-widescreen is-2-fullhd">
                    <address>
                        <img src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/ico-ubicacio.svg" alt="" width="30" height="30" class="is-block mb-4">
                        <?php echo tstring('footer_address'); ?>
                    </address>
                </div>

                <div class="column is-one-third-tablet is-one-fifth-widescreen is-2-fullhd">
                    <div class="is-flex gap-2 mb-4">
                        <img src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/ico-telefon.svg" alt="" width="30" height="30">
                        <img src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/ico-correu.svg" alt="" width="30" height="30">
                    </div>
                    <div class="flow--m">
                        <div>
                            <p><?php echo tstring('footer_visits') ?></p>
                            <p>
                                <a href="tel:<?php echo str_replace(' ', '', tstring('footer_visits_telephone')) ?>" class="has-text-weight-semibold"><?php echo tstring('footer_visits_telephone') ?></a> · Fax <?php echo tstring('footer_visits_fax') ?> <br>
                                <a href="mailto:<?php echo tstring('footer_visits_email') ?>"><?php echo tstring('footer_visits_email') ?></a>
                            </p>
                        </div>
                        <div>
                            <p><?php echo tstring('footer_general') ?></p>
                            <a href="tel:<?php echo str_replace(' ', '', tstring('footer_general_telephone')) ?>" class="has-text-weight-semibold"><?php echo tstring('footer_general_telephone') ?></a>
                        </div>
                    </div>
                </div>

                <div class="column is-one-third-tablet is-one-fifth-widescreen is-2-fullhd">
                    <img src="/tpl/assets/img/ico-horari.svg" alt="" width="30" height="30" class="mb-4 is-block">
                    <div class="flow--m">
                        <p><?php echo tstring('footer_visits_hours') ?></p>
                        <div>
                            <p><?php echo tstring('footer_visits_arranged') ?></p>
                            <p><?php echo tstring('footer_visits_arranged_hours') ?></p>
                        </div>
                    </div>
                </div>

                <div class="column is-hidden-touch is-hidden-desktop-only is-hidden-widescreen-only"></div>
                <div class="column is-full-tablet is-one-fifth-widescreen is-1-fullhd has-text-centered has-text-centered-desktop">
                    <p class="is-size-5 mb-4"><?php echo tstring('footer_found_in') ?>:</p>
                    <ul class="is-flex is-flex-wrap-wrap gap-3 is-justify-content-center">
                        <li>
                            <a href="https://twitter.com/muprevalencia">
                                <img src="/tpl/assets/img/ico-twitter.svg" alt="X" width="40" height="40" class="is-block">
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/mupreva/">
                                <img src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/ico-instagram.svg" alt="Instagram" width="44" height="44" class="is-block">
                            </a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/user/museuprehistoria">
                                <img src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/ico-youtube.svg" alt="YouTube" width="44" height="44" class="is-block">
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/mupreva/">
                                <img src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/ico-facebook.svg" alt="Facebook" width="40" height="40" class="is-block">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="is-flex is-flex-wrap-wrap gap-4 is-align-items-flex-end is-justify-content-center">
                <a href="https://www.dival.es/areadecultura/content/area-de-cultura" class="is-block"><img src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/logo-diva.jpg" srcset="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/logo-diva@2x.jpg 2x" width="129" height="65"></a>
                <ul class="is-flex is-flex-wrap-wrap gap-6 is-justify-content-center mx-auto is-size-6 has-text-weight-medium">
                <?php foreach ($this->menu_footer as $entry) : ?>
                    <li>
                        <a href="<?php echo __WEB_ROOT_WEB__ . '/'.$entry->web_path ?>"><?php echo $entry->title ?></a>
                    </li>
                    <?php endforeach ?>
                </ul>
            </div>
            <a href="#top" aria-label="<?php echo tstring('footer_to_top') ?>" class="scrolltop is-block ml-auto mb-4 pr-4">
                <svg width="50" height="50" xmlns="http://www.w3.org/2000/svg">
                    <g fill="none" fill-rule="evenodd">
                        <path fill="#000" d="M0 50h50V0H0z" />
                        <path stroke="#FFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M15 30.102 25.102 20l10.102 10.102" />
                    </g>
                </svg>
            </a>
        </div>
    </footer>
