    <header id="header" class="main-header is-relative">
        <!-- skip link -->
        <a href="#main-nav" class="skip-link"><?php echo tstring('header_jump_menu') ?></a>
        <a href="#main" class="skip-link"><?php echo tstring('header_jump_content') ?></a>
        <!-- /skip link -->


        <div class="wrapper is-flex is-justify-content-space-between">
            <!-- Logo -->
            <h1 class="site-logo is-size-7">
                <span class="is-flex gap-3 is-align-items-flex-end">
                    <img loading="lazy" src="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/ico-logo-mupreva.png" srcset="<?php echo __WEB_ROOT_WEB__ ?>/assets/img/ico-logo-mupreva@2x.png 2x" alt="" width="26" height="40" class="is-block">
                    <span class="has-text-white has-text-weight-semibold is-size-4 is-hidden-mobile is-hidden-widescreen-only"><?php echo WEB_ENTITY_LABEL ?></span>
                </span>

            </h1>
            <!-- /Logo -->
            <!-- Idiomes -->
            <?php $web_langs = json_decode(WEB_AR_LANGS); ?>
            <div class="lang">
                <div class="js-expandmore">
                    <span class="is-sr-only"><?php echo tstring('header_select_lang') ?>: </span>
                    <div class="is-hidden-mobile">
                        <?php echo $web_langs->{WEB_CURRENT_LANG_CODE}->name ?>
                    </div>
                    <div class="is-hidden-tablet">
                        <abbr title="<?php echo $web_langs->{WEB_CURRENT_LANG_CODE}->name ?>"><?php echo $web_langs->{WEB_CURRENT_LANG_CODE}->code ?></abbr>
                    </div>
                    <span class="is-sr-only">. <?php echo tstring('header_change_lang') ?></span>
                </div>
                <div class="js-to_expand">
                    <ul id="lang" class="has-background-black link-dn py-4 px-5 flow--2xs">
                        <?php foreach ($web_langs as $lang => $lang_info) :
                            if ($lang != WEB_CURRENT_LANG_CODE) :
                        ?>
                        <li>
                            <a hreflang="<?php echo $lang_info->code ?>" xml:lang="<?php echo $lang_info->code ?>" href="?lang=<?php echo $lang ?>" lang="<?php echo $lang_info->code ?>">
                                <?php echo $lang_info->name ?>
                            </a>
                        </li>
                        <?php
                            endif;
                        endforeach ?>
                    </ul>
                </div>
            </div>
            <!-- /Idiomes -->
            <!-- Search -->
            <div class="header-search">
                <div class="js-expandmore is-flex gap-2">
                    <div class="is-sr-only"><?php echo tstring('header_search') ?></div>
                </div>
                <div class="js-to_expand py-7 has-background-black">
                    <div class="wrapper">
                        <form action="/search" class="mx-auto">
                            <fieldset class="is-flex gap-4 is-align-items-center is-justify-content-center">
                                <legend class="is-sr-only"><?php echo tstring('header_search') ?></legend>
                                <div class="field mb-0">
                                    <label class="is-sr-only" for="search2"><?php echo tstring('header_search_button') ?></label>
                                    <div class="control">
                                        <input type="search" name="keywords" id="search2" value="" class="input">
                                    </div>
                                </div>
                                <button type="submit" class="is-flex-shrink-0">
                                    <img loading="lazy" src="/assets/img/ico-lupa.svg" alt="<?php echo tstring('header_search_button') ?>" width="26" height="40" class="is-block">
                                </button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /Search -->
            <!-- main-nav -->
            <nav class="navigation" id="main-nav">
                <div id="menu" class="main-nav">
                <?php echo $this->menu_tree_html ?>
                </div>
            </nav>
            <!-- /main-nav -->
        </div>
    </header>
