<header class="item_header">
    <!-- Logo -->
    <a class="link_header_logo" href="<?php echo __WEB_HOME_URL__ ?>">
        <img class="header_logo" src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/logo_museo_qdp.svg">
    </a>
    <!-- Item label -->
    <div id="item_label" class="item_label"></div>
    <!-- Button close -->
    <img class="close_button" title="<?php echo tstring('close') ?>" src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/icon_close_black.svg" onmousedown="page.close_window()">
</header>
