<?php if ((isset($body) && !empty($body)) || (isset($pdf) && !empty($pdf))) : ?>
<div class="wrapper">
    <div class="columns">
        <?php if (isset($body) && !empty($body)) : ?>
        <div class="column is-half-desktop flow text-base">
            <?php echo $body ?>
        </div>
        <?php endif ?>
        <?php if (isset($pdf) && !empty($pdf)) : ?>
        <div class="column is-half-desktop flow">
            <ul class="rows_container pub-text-results flow--l">
                <?php foreach ($pdf as $value) : ?>
                <li class="pb-6">
                    <div class="columns is-flex-direction-row-reverse">
                        <div class="column flow--2xs">
                            <div class="flow--2xs">
                                <h3 class="is-size-3 has-text-weight-normal">
                                    <a href="<?php echo $value['pdf'] ?>" target="_blank"><?php echo $value['title'] ?></a>
                                </h3>
                            </div>

                        </div>
                        <div class="column is-narrow">
                            <img loading="lazy" src="<?php echo $value['image'] ?>" width="102" height="132" alt="">
                        </div>
                    </div>
                </li>
                <?php endforeach ?>
            </ul>
        </div>
        <?php endif ?>
    </div>
</div>
<?php endif ?>
