<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Page Wrapper -->
<main class="main-content" id="main">
    <!-- Main wrapper -->
    <div class="wrapper">
        <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/breadcrumb.phtml'; ?>



        <div class="container">
            <article id="main">

                <!-- title -->
                <h2><?php echo $title ?></h2>

                <!-- abstract -->
                <p><?php echo $abstract ?></p>

                <!-- Result -->
                <section class="result">
                    <div id="rows_list"></div>
                    <div id="export_data" class="export_data_container"></div>
                </section>

            </article>
        </div>




    </div>
</main>
<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        outstanding.set_up({
            rows_list_container: document.getElementById('rows_list'),
            export_data_container: document.getElementById('export_data'),
            area_name: <?php echo json_encode($area_name) ?>
        })
    })
</script>
