<?php
# REQUIRED FILES
$base_path    = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Page Wrapper -->
<main class="main-content" id="main">
    <!-- Main wrapper -->
    <div class="wrapper">
        <?php include dirname(dirname(dirname(__FILE__))) . '/page/html/breadcrumb.phtml'; ?>


        <div class="container wide">
            <!-- Result -->
            <section class="result">
                <div id="filter" class="container"></div>
                <div id="rows_list"></div>
            </section>
        </div>

    </div>
</main>
<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
    dom_ready(function() {
        didactic.set_up({
            container: document.getElementById('rows_list'),
            filter_node: document.getElementById('filter'),
            grouper: <?php echo json_encode($grouper) ?>
        })
    })
</script>
